name: Generate Snake Animation

on:
  schedule:
    # Runs every day at 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: DanielGaudreault  # Replace with your GitHub username
          svg_output_path: assets/github-contribution-grid-snake.svg

      - name: Push the generated SVG to the repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/github-contribution-grid-snake.svg
          git commit -m "Update GitHub Contribution Snake"
          git push
